codecov:
  token: 44056013-3606-4f14-820c-952a4b3caf9d
  bot: "codecov-io"
  ci:
    - "travis.org"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
  parsers:
    jacoco:
      partials_as_hits: true #false by default