version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run unit tests
          command: mvn test

  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run unit tests
          command: mvn test
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - checkout
      - codecov/upload