version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: mvn test


  test:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run tests and collect coverage
          command: mvn test jacoco:report

  upload-to-codecov:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run tests and collect coverage
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml


workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master

  upload-to-codecov:
    jobs:
      - upload-to-codecov:
          requires:
            - test
            - build
          filters:
            branches:
              only: master
