version: 2.1

orbs:
  codecov: codecov/codecov@3.2.3

jobs:
  docs-build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: javadoc
          command: |
            mkdir -p docs/apidocs
            mvn javadoc:javadoc -D maven.javadoc.skip=false -D javadocDirectory=docs/apidocs
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout
      - run:
          name: Run unit tests
          command: mvn test


  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: mvn install
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check
      - run:
          name: Run tests and collect coverage
          command: mvn test jacoco:report
      - store_artifacts:
          path: target/site
          destination: rapport


  generate-javadoc:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - attach_workspace:
          at: target/site
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Configure Git for GitHub access
          command: |
            npm install need sudo
            git config --global user.name "ayoub-djaghloul"
            git config --global user.email "ayoub.djaghloul@alumni.univ-avignon.fr"
            sudo npm install -g gh-pages --save-dev
      - add_ssh_keys:
          fingerprints:
            - "SHA256:RtlidQXA3xL/33BmRmsHq62Yn7YgWCz6P9QXHs2nxPY"
      - run:
          name:  Deploy docs to gh-pages branch
          command: gh-pages --dist target/site/apidocs




  upload-to-codecov:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run tests and collect coverage
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml


workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - generate-javadoc:
          requires:
            - test
      - upload-to-codecov:
          requires:
            - test
