version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests and generate coverage report
          command: mvn test jacoco:report

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: mvn test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
  upload-to-codecov:
    jobs:
      - codecov/upload:
          context: org-global
          requires:
            - build
          filters:
            branches:
              only: master

