version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Run unit tests with code coverage
          command: mvn clean verify jacoco:report

      - codecov/upload:
          file: target/site/jacoco/jacoco.xml

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master