version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Run unit tests and generate coverage report
          command: mvn test jacoco:report

workflows:
  version: 2.1
  build_and_coverage:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - codecov/upload:
          requires:
            - build
          filters:
            branches:
              only: master
