version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk  # Utilisation de l'image Docker avec Java 8

    steps:
      - checkout  # Étape pour récupérer le code du repository

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run unit tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master  # Exécuter seulement pour la branche master
