version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build
          command: mvn compile

  test:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Prepare JaCoCo
          command: mvn jacoco:prepare-agent test jacoco:report
  codecov/upload:
    file: target/site/jacoco/jacoco.xml



workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
  codecov/upload:
    jobs:
      - checkout
      - codecov/upload